# Generated by Django 5.2 on 2025-05-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('survey_score', models.FloatField(default=0, verbose_name='Оценка опроса')),
                ('nps_score', models.FloatField(default=0, verbose_name='NPS')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Удовлетворенность клиентов',
                'verbose_name_plural': 'Удовлетворенность клиентов',
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('deals_closed', models.IntegerField(default=0, verbose_name='Закрытые сделки')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('efficiency_score', models.FloatField(default=0, verbose_name='Оценка эффективности')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Производственный показатель',
                'verbose_name_plural': 'Производственные показатели',
                'indexes': [models.Index(fields=['manager', 'date'], name='metrics_pro_manager_29f33d_idx')],
            },
        ),
    ]
