# Generated by Django 5.2 on 2025-05-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity_weight', models.FloatField(default=0.3, verbose_name='Вес производственных показателей')),
                ('customer_satisfaction_weight', models.FloatField(default=0.25, verbose_name='Вес удовлетворенности клиентов')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
            ],
            options={
                'verbose_name': 'Вес критериев оценки',
                'verbose_name_plural': 'Веса критериев оценки',
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='Период')),
                ('total_score', models.FloatField(verbose_name='Общий балл')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Оценка эффективности',
                'verbose_name_plural': 'Оценки эффективности',
                'unique_together': {('manager', 'period')},
            },
        ),
    ]
