# Generated by Django 5.0.4 on 2025-05-16 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фактора')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='FactorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='Период')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationfactor', verbose_name='Фактор')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
        ),
    ]
