# Generated by Django 5.2 on 2025-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(max_length=20, verbose_name='Период')),
                ('average_score', models.FloatField(verbose_name='Средний балл')),
            ],
            options={
                'verbose_name': 'Отчет по отделу',
                'verbose_name_plural': 'Отчеты по отделам',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название KPI')),
                ('target_value', models.FloatField(verbose_name='Целевое значение')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
            },
        ),
    ]
